package com.war.canadapanda.agents.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.FieldDefaults;

import java.util.List;

@DynamoDBTable(tableName = "Agent")
@Setter
@FieldDefaults(level = AccessLevel.PRIVATE)
@NoArgsConstructor
public class AgentModel {
    String agentid;
    String email;
    String firstName;
    String lastName;
    List<String> services;
    String primaryServiceKey;
    Integer phonenum;

    public AgentModel(String email, String firstName, String lastName,
                      List<String> services, String primaryServiceKey, Integer phonenum) {
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.services = services;
        this.primaryServiceKey = primaryServiceKey;
        this.phonenum = phonenum;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getAgentid() {
        return agentid;
    }

    @DynamoDBAttribute
    public String getEmail() {
        return email;
    }

    @DynamoDBAttribute
    public String getFirstName() {
        return firstName;
    }

    @DynamoDBAttribute
    public String getLastName() {
        return lastName;
    }

    @DynamoDBAttribute
    public List<String> getServices() {
        return services;
    }

    @DynamoDBAttribute
    public String getPrimaryServiceKey() {
        return primaryServiceKey;
    }

    @DynamoDBAttribute
    public Integer getPhonenum() {
        return phonenum;
    }
}
